### ISSUE TITLE
Relationship processing error

### ISSUE THREAD

**Issue by ariesomers** [dart-bridge/trestle#7]
When model have void methods, relationship parser fails with "Unsupported operation: void has no reflected type Dart" exception in _isValidRelationshipAssign method.
I suggest add something like 

```
  if (local.simpleName.toString() == "Symbol(\"void\")" || foreign.simpleName.toString() =="Symbol(\"void\")")
      return false;
```

at beginning of this method.

**Comment by emilniklas** [comment]
Thanks for reporting. Turns out I just needed to switch up the order in a few filters, to ensure that any relationship annotations are present before evaluating the return type of the field.

https://github.com/dart-bridge/trestle/commit/231aefce75b5fefa819f00053b30008c2a3a89a5

I'll publish 0.11.1 immediately

**Comment by ariesomers** [comment]
May be it would me more accurate, but I'm not sure, if it possible to fetch annotations for void field.

BTW, you're doing great job, thank you!
